name: Build index.json

on:
    push:
        branches: [main]
        paths: ["documents/**", "scripts/**", "pnpm-lock.yaml", ".github/workflows/build-index.yml"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write # 显式声明要写仓库

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0 # 解决「回推时报 ahead」问题

            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: "pnpm" # 把 pnpm store 也缓存起来

            - name: Install pnpm
              run: corepack enable

            - name: Install deps
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm run build

            # 关键：用 [skip ci] 防止触发新一轮 workflow
            - name: Commit & push if changed
              run: |
                  git config user.name  "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add data/index.json
                  git diff --cached --quiet || (
                    git commit -m "chore: update index.json [skip ci]"
                    git push
                  )
